=== RaphaelScursoni/XML-DTD-Treino3/revisoes.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT revisoes (veiculo+)>
<!ATTLIST veiculo placa CDATA #REQUIRED>
<!ATTLIST veiculo loja CDATA (Itu)>
<!ATTLIST veiculo combustivel CDATA (flex|gasolina|diesel) #REQUIRED>
<!ATTLIST veiculo zerokm CDATA (Sim|NÃ£o) #REQUIRED>
<!ELEMENT veiculo (descricao?, caracteristica+)>
<!ELEMENT caracteristica (cor, km?, foto+)>
<!ELEMENT cor (#PCDATA)>
<!ELEMENT km (#PCDATA)>
<!ELEMENT foto (#EMPTY)>
<!ELEMENT descricao (#PCDATA)>

=== RaphaelScursoni/XML-DTD-Treino3/revisoes.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE revisoes SYSTEM "revisoes.dtd">
<revisoes>
    <veiculo placa="ABC1234" combustivel="flex" zerokm="Não">
        <descricao>
            Veículo novo, único dono
        </descricao>
        <caracteristicas>
            <cor>Prata</cor>
            <km>14118</km>
            <foto>carro.png</foto>
        </caracteristicas>
    </veiculo>
    <veiculo placa="CBA1234" combustivel="gasolina" zerokm="Sim">
        <descricao>
            Veículo novo zero km.
        </descricao>
        <caracteristicas>
            <cor>Preto</cor>
            <foto>carro2.png</foto>
        </caracteristicas>
    </veiculo>
</revisoes>
